### ISSUE TITLE
Uncaught Typerror: Cannot read properties of undefined when using rawMetarToSVG

### ISSUE THREAD

**Issue by e4rthdog** [Phoenix-OpsGroup/metar-plot#32]
I am getting this error in a Vue3 project.

Function declaration:

`function getMetarSvg() {
  return metar_plot.rawMetarToSVG(
    "LGAV 090620Z 36016KT 320V020 9999 SCT025 27/17 Q1010 NOSIG",
    100,
    100,
    true
  );`

**Comment by jgunzelman-phoenix** [comment]
Can you post the whole output of your error?  I put your metar into https://phoenix-opsgroup.github.io/metar-plot-demo/
and it produces a plot.  This library only works on ES6 or typescript it will not work in ES5.

**Comment by jgunzelman88** [comment]
Marking resolved due to update and lack of response
